# Crowdin configuration for tsdmyanmar
# - Set the environment variable CROWDIN_API_TOKEN with your Crowdin API token before using the Crowdin CLI
# - The config syncs the source English JSON to language folders (e.g. i18n/mrh/common.json, i18n/my/common.json)

version: "2"

project_identifier: tsdmyanmar
api_token: $CROWDIN_API_TOKEN

# Local repo base path (relative to this file)
base_path: "."

# Source language used in source files
source_language: en

# Keep hierarchy as-is to match our i18n folder structure
preserve_hierarchy: true

files:
  - source: "news/source/en/*.json"
    translation: "news/%locale%/%original_file_name%"
    # Crowdin will write translated article files back to the repo under `news/{lang}/`
    export_patterns:
      - "news/%locale%/%original_file_name%"

  # Keep existing i18n common.json mapping alongside news content
  - source: "i18n/en/common.json"
    translation: "i18n/%locale%/common.json"
    languages:
      - mrh
      - my
    export_patterns:
      - "i18n/%locale%/common.json"

# Optional: add language mapping here if you need to map Crowdin locale codes to project codes
language_mapping:
  mrh: mrh
  my: my
