-- D1-compatible SQL to create and seed `updates` table
-- Run via Wrangler D1 CLI or the D1 admin UI

CREATE TABLE IF NOT EXISTS updates (
  id INTEGER PRIMARY KEY,
  date TEXT NOT NULL,
  title TEXT,
  summary TEXT,
  body TEXT
);

-- Seed entries (encoded JSON for title/summary/body)
INSERT OR REPLACE INTO updates (id, date, title, summary, body) VALUES
(1, '2026-01-10', '{"mrh":"Mara: TSD hla pauh a um chungtel project","en":"TSD launches new community project","my":"TSD သည် အသိုင်းအဝိုင်း ပရောဂျက် အသစ် မိတ်ဆက်သည်"}', '{"mrh":"Mara: Chungtel project nih a ruat lo chungtel khual.","en":"A short summary about the new community project launch.","my":"အသိုင်းအဝိုင်း ပရောဂျက် စတင်ခြင်း အကျဉ်းချုပ်။"}', NULL),
(2, '2026-01-05', '{"mrh":"Mara: Volunteer hriatna — March 2026","en":"Volunteer call — March 2026","my":"Volunteer ခေါ်ယူခြင်း — ၂၀၂၆ မတ်"}', '{"mrh":"Mara: Outreach program ah volunteer ngaihna nih.","en":"Seeking volunteers for upcoming outreach programs.","my":"လာမည့် outreach အစီအစဉ်များအတွက် volunteer များကို ရှာနေပါသည်။"}', NULL),
(3, '2025-12-15', '{"mrh":"Community water system handover","en":"Community water system handover","my":"ရွာသို့ ရေထောက်ပံ့ရေး စနစ် ပေးအပ်ပွဲ"}', '{"mrh":"Hniangpu paa...","en":"Local stakeholders and water committee participated in the handover.","my":"ဒေသခံတို့နှင့် ရေကော်မတီတို့ပါဝင်သော ပေးအပ်ပွဲ။"}', NULL),
(4, '2025-10-30', '{"mrh":"Rice distribution — relief","en":"Rice distribution — relief","my":"ထောက်ပံ့ရေး သန့်ရှင်းစက်မှု"}', '{"mrh":"Tla...","en":"Emergency rice distribution in response to floods.","my":"နွေဦး ရာသီမိုးရေကြောင့် ကူညီထောက်ပံ့မှု"}', NULL),
(5, '2024-08-01', '{"mrh":"Teacher training cohort 2","en":"Teacher training cohort 2","my":"ဆရာ/ဆရာမများ လေ့ကျင့်ရေး"}', '{"mrh":"Khai...","en":"Second cohort graduated from our teacher training program.","my":"ဒုတိယလစာကို သင်တန်းပြီးစီးခဲ့သည်။"}', NULL),
(6, '2023-05-18', '{"mrh":"Health outreach summary","en":"Health outreach summary","my":"ကျန်းမာရေး အက်ဖ်ဂ်"}', '{"mrh":"Su...","en":"Summary of community health outreach and referrals.","my":"ကျန်းမာရေး အစီရင်ခံစာအကျဉ်း"}', NULL),
(7, '2026-01-11', '{"mrh":"Solar pumps project tawng in","en":"Solar pumps installation project","my":"နေရောင်စွမ်းအား ရေတိုးစနစ် တပ်ဆင်ခြင်း"}', '{"mrh":"Solar pumps nih hman lo in a ruat hna.","en":"Installing solar pumps to improve access to clean water.","my":"ရေသန့်ရရှိရေးအတွက် နေရောင်စွမ်းအားပန် တပ်ဆင်ခြင်း။"}', '{"mrh":"<p>Ko project nih paikhat a si. <img src=\"https://via.placeholder.com/800x400?text=Solar+Pumps\" alt=\"Solar pumps\" style=\"max-width:100%\"> </p><p><iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ScMzIvxBSi4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></p><p><a href=\"/assets/documents/reports/solar-pumps-report.pdf\" target=\"_blank\">Download the project report (PDF)</a></p>","en":"<p>Our team installed solar-powered water pumps to support clean water access in remote villages. <img src=\"https://via.placeholder.com/800x400?text=Solar+Pumps\" alt=\"Solar pumps\" style=\"max-width:100%\"></p><p><iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ScMzIvxBSi4\" title=\"Project video\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></p><p><a href=\"/assets/documents/reports/solar-pumps-report.pdf\" target=\"_blank\">Download the full project report (PDF)</a></p>","my":"ကျွန်တော်တို့အဖွဲ့သည် ခေတ်မီ နေရောင်စွမ်းအား ရေမောင်းစက်များကို ရွာလေးများတွင် တပ်ဆင်ခဲ့ပြီး ရေသန့်ရရှိရေးကို ကူညီပေးပါသည်။ <img src=\"https://via.placeholder.com/800x400?text=Solar+Pumps\" alt=\"Solar pumps\" style=\"max-width:100%\"></p><p><iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ScMzIvxBSi4\" title=\"Project video\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></p><p><a href=\"/assets/documents/reports/solar-pumps-report.pdf\" target=\"_blank\">အစီရင်ခံစာကို ဒေါင်းလုပ်ဆွဲရန် (PDF)</a></p>"}'),
(8, '2025-11-20', '{"mrh":"Volunteer story — Hriatna","en":"Volunteer spotlight — Hriatna","my":"Volunteer အားပေးသူများ — Hriatna"}', '{"mrh":"Volunteer nih community outreach ah hman tet.","en":"A volunteer story from our outreach in November.","my":"ဒီ ဗဟိုသတင်းတွင် volunteer အကြောင်းအရာ။"}', '{"mrh":"<p>Hriatna nih volunteer tan sawn lei. <img src=\"https://via.placeholder.com/800x400?text=Volunteer+Hriatna\" alt=\"Volunteer Hriatna\" style=\"max-width:100%\"></p><p><a href=\"https://example.org/volunteer-signup\" target=\"_blank\">Volunteer sign-up</a></p>","en":"<p>Meet Hriatna, one of our dedicated volunteers. <img src=\"https://via.placeholder.com/800x400?text=Volunteer+Hriatna\" alt=\"Volunteer Hriatna\" style=\"max-width:100%\"></p><p><a href=\"https://example.org/volunteer-signup\" target=\"_blank\">Sign up to volunteer</a> or <a href=\"/contact.html\">contact us</a> for more information.</p>","my":"<p>Hriatna သည် ကျွန်ုပ်တို့၏ အလှူရှင်တစ်ဦးဖြစ်သည်။ <img src=\"https://via.placeholder.com/800x400?text=Volunteer+Hriatna\" alt=\"Volunteer Hriatna\" style=\"max-width:100%\"></p><p><a href=\"https://example.org/volunteer-signup\" target=\"_blank\">Volunteer အဖြစ် လျှောက်လွှာ</a> သို့မဟုတ် <a href=\"/contact.html\">ဆက်သွယ်ရန်</a>။</p>"}'),
(9, '2025-07-05', '{"mrh":"Health outreach — Photo gallery","en":"Health outreach — Photo gallery","my":"ကျန်းမာရေး outreach — ဓာတ်ပုံပြခန်း"}', '{"mrh":"Local clinic outreach report and gallery.","en":"Summary and photo gallery from our health outreach.","my":"ကျန်းမာရေး outreach အကျဉ်းနှင့် ဓာတ်ပုံပြခန်း"}', '{"mrh":"<p>Clinic outreach provided screenings and referrals. <img src=\"https://via.placeholder.com/800x400?text=Health+Outreach\" alt=\"Health outreach\" style=\"max-width:100%\"></p><p><a href=\"/gallery/health-outreach\">View photo gallery</a> • <a href=\"/assets/documents/reports/health-outreach-data.csv\" target=\"_blank\">Download data (CSV)</a></p>","en":"<p>We provided screenings and referrals at the local clinic. <img src=\"https://via.placeholder.com/800x400?text=Health+Outreach\" alt=\"Health outreach\" style=\"max-width:100%\"></p><p><a href=\"/gallery/health-outreach\">View the photo gallery</a> • <a href=\"/assets/documents/reports/health-outreach-data.csv\" target=\"_blank\">Download the data (CSV)</a></p>","my":"<p>ကျန်းမာရေး စစ်ဆေးရေးများနှင့် အကြံပြုချက်များ ပေးအပ်ခဲ့သည်။ <img src=\"https://via.placeholder.com/800x400?text=Health+Outreach\" alt=\"Health outreach\" style=\"max-width:100%\"></p><p><a href=\"/gallery/health-outreach\">ဓာတ်ပုံပြခန်းကို ကြည့်ရန်</a> • <a href=\"/assets/documents/reports/health-outreach-data.csv\" target=\"_blank\">ဒေတာကို ဒေါင်းလုဒ် (CSV)</a></p>"}');

-- You can add more INSERT statements from your `assets/documents/reports/updates.json` as needed
